name: "NixOS CI"

on:
  push:
    branches: ["main", "working*"]
  pull_request:
    branches: ["main"]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: ryzengrind-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: false
          extraPullNames: nix-community, ryzengrind, daimyo, bopbopbleedem

      - name: Update Flake Inputs
        run: nix flake update

      - name: Check Flake
        run: nix flake check

      - name: Check flake formatting
        run: nix fmt

  module-test:
    needs: flake-check
    strategy:
      matrix:
        module: [wsl] # Only test WSL initially
        include:
          - module: wsl
            test-gui: true
            test-cuda: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ryzengrind-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run module tests
        run: |
          # Test basic module functionality
          nix build .#nixosTests.${{ matrix.module }} -L \
            --option sandbox false \
            --show-trace

          # Test GUI support if enabled
          if [[ "${{ matrix.test-gui }}" == "true" ]]; then
            nix build .#nixosTests.${{ matrix.module }}-gui -L \
              --option sandbox false \
              --show-trace
          fi

          # Test CUDA support if enabled
          if [[ "${{ matrix.test-cuda }}" == "true" ]]; then
            nix build .#nixosTests.${{ matrix.module }}-cuda -L \
              --option sandbox false \
              --show-trace
          fi

  test-configurations:
    needs: module-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [daimyo]
        include:
          - host: daimyo
            test-wsl: true
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Test build process
        run: |
          # Update flake inputs
          nix flake update

          # Check flake configuration
          nix flake check --show-trace

          # Test build steps sequentially
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --dry-run

          # Test activation script
          nix eval .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.drvPath

      - name: Test WSL configuration
        if: matrix.test-wsl
        run: |
          # Test NixOS-WSL module loading
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.wsl.enable

          # Verify WSL-specific configurations
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.environment.systemPackages | grep -q "wslu"
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.environment.systemPackages | grep -q "wsl-open"

  security-scan:
    needs: test-configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23

      - name: Run security checks
        run: |
          # Run statix for static analysis
          nix run nixpkgs#statix -- check

          # Build the system first
          nix build .#nixosConfigurations.daimyo.config.system.build.toplevel

          # Run vulnix for vulnerability scanning
          nix run nixpkgs#vulnix -- --system ./result

  deploy:
    needs: [security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23

      - name: Deploy configurations
        run: |
          # Final build check before deployment
          nix build .#nixosConfigurations.daimyo.config.system.build.toplevel --dry-run

          # Deploy to Cachix
          nix path-info --json \
            .#nixosConfigurations.daimyo.config.system.build.toplevel | \
            jq -r '.[].path' | \
            xargs nix copy --to "s3://ryzengrind-nix-cache?region=us-east-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
