name: "NixOS Test"

on:
  push:
    branches: ["main", "working*"]
  pull_request:
    branches: ["main"]

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64-linux, aarch64-linux]
        profile: [base, dev, gaming, server]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            system = ${{ matrix.architecture }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ryzengrind-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run architecture tests
        run: |
          nix build .#nixosTests.${{ matrix.profile }}-${{ matrix.architecture }} -L \
            --option system ${{ matrix.architecture }} \
            --option sandbox false \
            --show-trace

  test-configurations:
    needs: matrix-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [daimyo00]
        include:
          - host: daimyo00
            test-wsl: true
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Test WSL configuration
        if: matrix.test-wsl
        run: |
          # Test NixOS-WSL module loading
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.wsl.enable

          # Verify WSL-specific configurations
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.environment.systemPackages | grep -q "wslu"
          nix eval --json .#nixosConfigurations.${{ matrix.host }}.config.environment.systemPackages | grep -q "wsl-open"

  security-scan:
    needs: [test-configurations]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v23

      - name: Run security checks
        run: |
          # Run statix for static analysis
          nix run nixpkgs#statix -- check

          # Build the system first
          nix build .#nixosConfigurations.daimyo00.config.system.build.toplevel

          # Run vulnix for vulnerability scanning
          nix run nixpkgs#vulnix -- --system ./result
